
version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./client/lib/.env.local
    environment:
      - NEXT_PUBLIC_FIREBASE_API_KEY
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - NEXT_PUBLIC_FIREBASE_APP_ID
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run start"
    ports:
      - "3111:3000"
#   db:
#     image: mysql:5.7
#     platform: linux/x86_64
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: portfolio
#       MYSQL_DATABASE: portfolio
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: portfolio
#     volumes:
#       - ./db:/var/lib/mysql
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

  