export const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_APIKEY || '';
export const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN || '';
export const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECTID || '';
export const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET || '';
export const FIREBASE_MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID || '';
export const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APPID || '';
export const FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID || '';

